services:
  db:
    container_name: postgres
    image: postgres:17.2
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  demo-api:
    container_name: demo-api
    image: downloa27/demo-api
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
    command:
      - --spring.datasource.url=jdbc:postgresql://db:5432/customer

  demo-frontend-react:
    container_name: demo-react
    image: downloa27/demo-react
    build:
      context: frontend/demo-react
      args:
        api_base_url: http://localhost:8080
    ports:
      - "3000:5173"
    depends_on:
      - demo-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: