services:
  db:
    container_name: postgres
    image: postgres:17.4
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  demo-api:
    container_name: demo-api
    image: downloa27/demo-api
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
    command:
      - --spring.datasource.url=jdbc:postgresql://db:5432/customer

networks:
  db:
    driver: bridge

volumes:
  db: